/**
 * We will define the sidebars here.
 */
module.exports = {
  'get-started': [{
    type: 'autogenerated',
    dirName: './get-started',
  }],
  datasets: [
    'datasets/introduction',
    'datasets/create',
    'datasets/import',
    {type: 'category', label: 'Resources', items: ['datasets/resources/billing']}
  ],
  models: [{
    type: 'autogenerated',
    dirName: './models',
  }]
};
