name: Deploy to Google Storage
on:
  push:
    branches: [main]
    tags: ['**']
jobs:
  format:
    name: Format with Prettier
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'
          registry-url: https://npm.pkg.github.com
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Run Prettier
        run: npm run format:check
  lint:
    name: Lint with ESLint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'
          registry-url: https://npm.pkg.github.com
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint
  build:
    name: Build static content
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: static-content
          path: build/
  docker:
    name: Build Docker image
    needs: [build]
    runs-on: ubuntu-20.04
    outputs:
      image: ${{ steps.square.outputs.image-release }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Square
        id: square
        uses: mathieu-bour/square@0.1.0
      - name: Setup Google Cloud SDK
        uses: mathieu-bour/setup-gcloud@1.3.0
        with:
          version: local
          service-account-key: ${{ secrets.GCLOUD_AUTH }}
          configure-docker: europe-west6-docker.pkg.dev
      - name: Download static content from artifact
        uses: actions/download-artifact@v2
        with:
          name: static-content
          path: build/
      - name: Build Docker image
        run: |
          docker build \
            --tag=${{ steps.square.outputs.image-release }} .
        env:
          DOCKER_BUILDKIT: '1'
      - name: Push Docker Image to Artifact Registry
        run: docker push ${{ steps.square.outputs.image-release }}
  deploy:
    name: Deploy to Google Cloud Run
    needs: [format, lint, docker]
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Google Cloud SDK
        uses: mathieu-bour/setup-gcloud@1.3.0
        with:
          version: local
          service-account-key: ${{ secrets.GCLOUD_AUTH }}
          configure-docker: europe-west6-docker.pkg.dev
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy docs-csquare-run \
            --image=${{ needs.docker.outputs.image }} \
            --region=europe-west1 \
            --cpu=1 \
            --memory=128Mi \
            --platform=managed \
            --port=80 \
            --allow-unauthenticated
