
name: Deploy to Google Storage
on:
  push:
    branches: [main]
    tags: ['**']
jobs:
  build:
    name: Build static content
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Setup Google Cloud SDK
        uses: mathieu-bour/setup-gcloud@1.3.0
        with:
          version: local
          service-account-key: ${{ secrets.GCLOUD_AUTH }}
          configure-docker: europe-west6-docker.pkg.dev
      - name: Remove old content from bucket
        shell: bash
        run: gsutil rsync -d -r build/ gs://docs.csquare.run
