
name: Deploy to Google Storage
on:
  push:
    branches: [main]
    tags: ['**']
  pull_request:
    types: [ opened, reopened, synchronize ]
jobs:
  square:
    name: Generate square metadata
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run square
        id: square
        uses: mathieu-bour/square@0.3.0
    outputs:
      environment: ${{ steps.square.outputs.environment }}
      ref-type: ${{ steps.square.outputs.ref-type }}
      version: ${{ steps.square.outputs.version }}
      semver: ${{ steps.square.outputs.semver }}
      image: ${{ steps.square.outputs.image }}
      image-tag: ${{ steps.square.outputs.image-tag }}
      image-tag-latest: ${{ steps.square.outputs.image-tag-latest }}
  build:
    name: Build
    needs: square
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Google Cloud SDK
        uses: mathieu-bour/setup-gcloud@1.3.0
        with:
          version: local
          service-account-key: ${{ secrets.GCLOUD_AUTH }}
          configure-docker: europe-west6-docker.pkg.dev
      - name: Install the latest buildkit release
        run: |
          BUILDKIT_URL="$(curl -sL https://api.github.com/repos/moby/buildkit/releases \
          | jq -r 'map(select(.name|startswith("v")))|sort_by(.name)[-1].assets[]|select(.name|endswith(".linux-amd64.tar.gz")).browser_download_url')"
          curl -L "${BUILDKIT_URL}" | sudo tar -xz -C /usr/local
      - name: Start buildkit daemon
        run: |
          sudo --non-interactive --shell <<END_SUDO
            install -d -m 0750 -o root -g docker /run/buildkit
            buildkitd &
            while ! test -S /run/buildkit/buildkitd.sock; do sleep 0.1; done
            chgrp docker /run/buildkit/buildkitd.sock
          END_SUDO
      - name: Build docker image
        run: |
          buildctl build \
            --frontend=dockerfile.v0 --local dockerfile=. --local context=. \
            --export-cache type=registry,ref="${{ needs.square.outputs.image }}:build-cache",mode=max \
            --import-cache type=registry,src="${{ needs.square.outputs.image }}:build-cache" \
            --output type=image,name=${{ needs.square.outputs.image-tag }}, push=true
  deploy:
    name: Deploy to Google Cloud Run
    needs: build
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    steps:
      - name: Setup Google Cloud SDK
        uses: mathieu-bour/setup-gcloud@1.3.0
        with:
          version: local
          service-account-key: ${{ secrets.GCLOUD_AUTH }}
          configure-docker: europe-west6-docker.pkg.dev
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy docs-csquare-run \
            --image=${{ needs.square.outputs.image-tag }} \
            --region=europe-west1 \
            --cpu=1 \
            --memory=128Mi \
            --platform=managed \
            --port=80 \
            --allow-unauthenticated

