
name: Deploy to Google Storage
on:
  push:
    branches: [main]
    tags: ['**']
jobs:
  build:
    name: Build static content
    runs-on: ubuntu-20.04
    steps:
      - name: Build
        run: yarn build
      - name: Setup Google Cloud SDK
        uses: mathieu-bour/setup-gcloud@1.3.0
        with:
          version: local
          service-account-key: ${{ secrets.GCLOUD_AUTH }}
          configure-docker: europe-west6-docker.pkg.dev
      - name: Upload static content
        shell: bash
        run: |
          gsutil cp build/ gs://docs.csquare.run